set(SRC_FILES
	Cursor.cpp
	draw_test.cpp
	InitScreen.cpp
	main.cpp
	TheApp.cpp
	character/character.cpp
	character/moster.cpp
	character/Monsters/AcidSlimeL.cpp
	Draw/Atlas_Region.cpp
	Draw/Draw_2D.cpp
	Draw/Image_Region.cpp
	Draw/ReText.cpp
	Draw/ReTexture.cpp
	Draw/Text_layout.cpp
	Game_object/action/Actions.cpp
	Game_object/action/Action_group.cpp
	Game_object/action/Action_group_handler.cpp
	Game_object/action/Card_use_action.cpp
	Game_object/action/Damage_action.cpp
	Game_object/action/Discard_action.cpp
	Game_object/action/Discard_all_action.cpp
	Game_object/action/Draw_card_action.cpp
	Game_object/action/Empty_shuffle_action.cpp
	Game_object/action/Wait_action.cpp
	Game_object/card/Cards.cpp
	Game_object/card/Card_group.cpp
	Game_object/card/Card_group_handler.cpp
	Game_object/card/Card_soul.cpp
	Game_object/card/red/Anger.cpp
	Game_object/card/red/Strike_red.cpp
	Game_object/character/Characters.cpp
	Game_object/character/Monster/Monsters.cpp
	Game_object/character/Monster/TempMonster.cpp
	Game_object/dungeon/Dungeons.cpp
	Game_object/dungeon/Dungeon_BottomScene.cpp
	Game_object/dungeon/Dungeon_manager.cpp
	Game_object/dungeon/Dungeon_screen.cpp
	Game_object/effect/Card_flash.cpp
	Game_object/effect/Card_glow_border.cpp
	Game_object/effect/Card_trail_effect.cpp
	Game_object/effect/Effects.cpp
	Game_object/effect/Effect_group.cpp
	Game_object/map/Dungeon_map.cpp
	Game_object/map/Map_dot.cpp
	Game_object/map/Map_edge.cpp
	Game_object/map/Map_generator.cpp
	Game_object/map/Map_node.cpp
	Game_object/room/Monster_room.cpp
	Game_object/scene/Bottom_scene.cpp
	Game_object/scene/Scenes.cpp
	RUtil/All_Image.cpp
	RUtil/Atlas_Reader.cpp
	RUtil/Game_Input.cpp
	RUtil/Hitbox.cpp
	RUtil/Image_book.cpp
	RUtil/Random.cpp
	RUtil/Some_Math.cpp
	RUtil/Text_Vector_Reader.cpp
)

set(INCLUDE_FILES
	Cursor.hpp
	draw_test.hpp
	InitScreen.hpp
	TheApp.hpp
	WindowSize.hpp
	character/character.hpp
	character/monster.hpp
	character/Monsters/AcidSlimeL.hpp
	character/Monsters/MonsterAction.hpp
	Draw/Atlas_Region.hpp
	Draw/Draw_2D.hpp
	Draw/Image_Region.hpp
	Draw/ReText.hpp
	Draw/ReTexture.hpp
	Draw/Text_layout.hpp
	Game_object/Group_template.hpp
	Game_object/action/Actions.hpp
	Game_object/action/Action_group.hpp
	Game_object/action/Action_group_handler.hpp
	Game_object/action/Card_use_action.hpp
	Game_object/action/Damage_action.hpp
	Game_object/action/Discard_action.hpp
	Game_object/action/Discard_all_action.hpp
	Game_object/action/Draw_card_action.hpp
	Game_object/action/Empty_shuffle_action.hpp
	Game_object/action/Wait_action.hpp
	Game_object/card/Cards.hpp
	Game_object/card/Card_group.hpp
	Game_object/card/Card_group_handler.hpp
	Game_object/card/Card_item.hpp
	Game_object/card/Card_soul.hpp
	Game_object/card/red/Anger.hpp
	Game_object/card/red/Strike_red.hpp
	Game_object/character/Characters.hpp
	Game_object/character/Player.hpp
	Game_object/character/Monster/Monsters.hpp
	Game_object/character/Monster/TempMonster.hpp
	Game_object/dungeon/Dungeons.hpp
	Game_object/dungeon/Dungeon_BottomScene.hpp
	Game_object/dungeon/Dungeon_manager.hpp
	Game_object/dungeon/Dungeon_screen.hpp
	Game_object/effect/Card_flash.hpp
	Game_object/effect/Card_glow_border.hpp
	Game_object/effect/Card_trail_effect.hpp
	Game_object/effect/Effects.hpp
	Game_object/effect/Effect_group.hpp
	Game_object/interface/Is_screen.hpp
	Game_object/map/Dungeon_map.hpp
	Game_object/map/Map_dot.hpp
	Game_object/map/Map_edge.hpp
	Game_object/map/Map_generator.hpp
	Game_object/map/Map_node.hpp
	Game_object/room/Monster_room.hpp
	Game_object/room/Rooms.hpp
	Game_object/scene/Bottom_scene.hpp
	Game_object/scene/Scenes.hpp
	RUtil/All_Image.hpp
	RUtil/Atlas_Reader.hpp
	RUtil/Game_Input.hpp
	RUtil/Hitbox.hpp
	RUtil/Image_book.hpp
	RUtil/Random.hpp
	RUtil/Random_package.hpp
	RUtil/Some_Math.hpp
	RUtil/Text_Vector_Reader.hpp
)

set(TEST_FILES
)